---
title: "LmImpute"
description: |
  Imputation by weighted regeression, using lm, allowing multiple explanatory variables and multiple response variables. Impute missing and wrong values (category 3) by the model based on representative data (category 1). Some data are considered correct but not representative (category 2)
author:
  - name: Kostra
    url: https://github.com/statisticsnorway/Kostra
date: 2021-11-24
output:
  distill::distill_article:
    self_contained: false
categories:
  - R
  - dataediting
  - imputation
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Kostra)
z = data.frame(  # Same example as in Thorud et.al (2010).
        x = c(1.1, 2.2, 3.3, 4.4, 5.5),
         y = c(2.3, 3.1, 3.2, 3.7, 4.5))
LmImpute(z)  # Simple regression
LmImpute(z, model = "y~x-1", weights = "1/x")  # Ratio model

rateData <- KostraData("rateData")               # Real Kostra data set
w <- rateData$data[, c(16, 5, 14, 15, 19)]
w <- w[is.finite(w[,"Ny.kostragruppe"]), ]       # Remove Longyearbyen
w[w[,"Ny.kostragruppe"]>13,"Ny.kostragruppe"]=13 # Combine small strata
names(w) = c("x", "y", "y14", "y15", "k")

# Ratio model within each strata assumming common variance
LmImpute(w, "y~x:factor(k)-1", weights = "1/x", estimationGroup = w$k)

# Similar to above, but two y variables
LmImpute(w, "cbind(y14,y15)~x:factor(k)-1", weights = "1/x", estimationGroup = w$k)

# Using transformation and "BackTransform"
LmImpute(w, "sqrt(y)~x",BackTransform = function(x) x^2,returnYHat = TRUE)

# Direct imputation of x
LmImpute(w, "I(y-x)~0",weights = "1/x",
  BackTransform = function(y){return(y+dynGet("data")$x)},
  limitModel = Inf, limitIterate = Inf, limitImpute = Inf,
  returnYHat = TRUE)
```


