project:
  type: website
  output-dir: docs

website:
  title: "Metodebiblioteket"
  description: |
    Metodebibliotek
  repo-url: https://github.com/statisticsnorway/metodebibliotek

  navbar:
    background: primary
    logo: "pictures/logo_kule.jpg"
    logo-href: index.html
    left:
      - text: "Alle funksjoner"
        href: catalog.qmd
      - text: "Veiledning"
        href: daplalab.qmd
      - text: "Status"
        href: status.qmd
    right:
      - icon: github
        menu:
          - text: "Source Code"
            url:  https://github.com/statisticsnorway/metodebibliotek
          - text: "Report a Bug"
            url:  https://github.com/statisticsnorway/metodebibliotek/issues
    pinned: true
    
  sidebar: 
    - title: "Alle funksjoner"
      style: "docked"
      background: light
      search: false
      collapse-level: 2
      contents:
        - text: Katalog
          href: catalog.qmd
        - text: Processmodell
          href: prosess.qmd
        - text: Metodeområde
          contents:
            - catalogue_edit.qmd
            - catalogue_est.qmd
            - catalogue_conf.qmd
            - catalogue_sesong.qmd 
    
    - title: "Veiledning"
      contents:
        - daplalab.qmd
        - rogpython.qmd
        - bidra.qmd
    
    - title: "Status"
      contents: 
        - status.qmd
        
format: 
  html: 
    theme: ssb.scss
    grid:
      sidebar-width: 250px
      margin-width: 250px
  
editor: source  


