---
title: "Bidra til Metodebiblioteket"
format:
  html:
    echo: false
    page-layout: full
editor: source

---

Har du brukt en metodiske funksjon som du mener kan være nyttig for andre i SSB? Da kan det vurderes for Metodebiblioteket. Selve kode for funksjonen skal ikke ligge i biblioteket siden dette er en metapakke. Den referere til andres pakker men samle en liste over nyttige metodiske funksjoner for offisiell statistikk. 

Her finner du veiledning om hvordan du kan bidra til Metodebiblioteket med en funksjon. 

1. **Clone repository og lage en ny branch**:
Clone repository fra [github](https://github.com/statisticsnorway/metodebiblioteket). Dette kan du gjøre fra terminalet eller fra  RStudio for eksempel. Lage en ny branch for endringer. 

2. **Legg funksjonen inn i create_table.R**: 
Åpne filen som ligger under "internal" som heter "create_table.R". Legg inn en ny rad med funksjonen "add_func()". Skriv navn av funksjonen, pakkenavn og stikkord. Standard stikkord som skal brukkes ligger på [Readme filen til repository](https://github.com/statisticsnorway/metodebiblioteket/blob/master/README.md#n%C3%B8kkelord). Skriv gjerne inn (GSBPM) prosessnummer i stikkord også. 

3. **Kjør add_func()**:
Kjør den nye raden du har skrevet som inkludere *add_func()*. Dette oppdatere datafil som ligger bak Metodebiblioteket.

4. **Legg pakken som brukes inn i DESCRIPTION fil**: 
Hvis du har lagt inn en ny R funksjon skal pakken også ligge i DESCRIPTION filen under imports. Dette er for at Metodebiblioteket skal også fungere som en metapakke. Hvis pakken ligger der fra før er det ikke nødvendig å legge det inn på nytt.

5. **Skriv en enhetstest til funksjonen**: 
For å forsikre kvalitet til funksjonene vi inkluderer i Metodebiblioteket har vi et mål at alle funksjoner skal har minst en enhetstest. Disse testene kjøres automatisk ved endring til hoved branch for å sjekke at funksjoner fungere som de skal. For mer informasjon om enhetstest se [Hvordan å skrive enhetstester](https://statisticsnorway.github.io/ssb-metodebiblioteket/enhetstester.html).

6. **Commit og push endringer til github**:
Commit og push endringer til github. Alle endringer til create_table.R filen, data filen ("katalogdata.csv"), hjelpefiler (DESCRIPTION og reexports.R), og enhetstester skal inkluderes. Til slutt, lage en pull request for å merge branch inn til main som da starter oppdatering av nettsiden automatisk.

