---
title: "Integrering av R og Python"
format:
  html:
    echo: false
    page-layout: full
editor: source
---

Mange av funksjonene i Metodebiblioteket er skrevet i R, mens de fleste i SSB utvikler produksjonsløpene sine i Python. På denne siden finner du tips til hvordan du kan bruke R-funksjoner fra Python - og motsatt. 

- Hvis du har et Python-produksjonsløp, men ønsker å bruke en enkel R-funksjon, se [Bruk av RWrapR](#sec-rwrapr)
- Hvis du har et Python-produksjonsløp, men ønsker å bruke én eller flere R-funksjoner til en relativt kompleks oppgaver, eller som involverer flere steg, se [Kjøring av R-skriptfiler fra Python](#sec-subprocess)
- Hvis du har et R-produksjonsløp, men ønsker å bruke en Python-funksjon, se [Kjøring av Python funksjoner i R med reticulate](#sec-reticulate)


## Bruk av RWrapR {#sec-rwrapr}
Python-pakken [RWrapR](https://pypi.org/project/rwrapr/) ble utviklet under Hack4SSB 2024. Den ligger på PyPI og er tilgjengelig for alle. Pakken gjør R-funksjoner tilgjengelige direkte i Python-miljøet. Dette kan være en god løsning når du kun ønsker å bruke én R-funksjon i et ellers Python-basert produksjonsløp. 

Pakken er fortsatt under utvikling og mangler noe funksjonalitet, for eksempel håndtering av manglende data, så vær forsiktig og test godt. Pakken RWrapR kan installeres fra PYPI med:

```bash
poetry add rwrapr
```
Se videoen under og koden [rwrapr_kjoring.py](https://github.com/statisticsnorway/ssb-metodebiblioteket/blob/main/Python-og-R/rwrapr_kjoring.py) for eksempler.

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/1145878640?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Kjør R funksjoner i Python med RWrapR"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

For mer detaljer, se [dokumentsidene for RWrapR](https://statisticsnorway.github.io/ssb-rwrapr/).


## Kjøring av R-skriptfiler fra Python {#sec-subprocess}
Selvstendige R-skriptfiler kan kjøres fra Python ved hjelp av et kall til terminalen med `Rscript`. Med «selvstendige» menes programmer som kan kjøres uavhengig, uten avhengighet til andre systemer eller variabler som allerede ligger i minnet. Fordelen med denne metoden er at den benytter renv-miljøet og gi bedre kontroll over håndtering av datatyper, manglende verdier og lignende, ettersom dette kan verifiseres ved å kjøre programmet direkte i R.

Vi anbefaler å bruke [subprocess](https://docs.python.org/3/library/subprocess.html) i Python for å utføre kjøringen. For eksempel, for å kjøre et R-skript med navn `lage_statistikk.R`, kan følgende kode benyttes:

```python
import subprocess

subprocess.run(["Rscript", "lager_statistikk.R"])
```
Se videoen under og kode [subprocess_kjoring.py](https://github.com/statisticsnorway/ssb-metodebiblioteket/blob/main/Python-og-R/subprocess_kjoring.py) for eksempler.

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/1145878687?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Kjøre R-skript fra Python med subprocess"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>


## Kjøring av Python-funksjoner i R med reticulate {#sec-reticulate}
Python-funksjoner kan kjøres direkte fra R ved hjelp av pakken [reticulate](https://rstudio.github.io/reticulate/). Denne pakken gjør det mulig å integrere Python-kode i R-skript, og gir dermed en fleksibel løsning når R-produksjonsløp krever funksjonalitet fra Python.
Fordelen med denne metoden er at den gir sømløs integrasjon mellom R og Python, inkludert deling av objekter mellom språkene. Dette gjør det enklere å kombinere styrkene fra begge miljøer i én arbeidsflyt.
For å bruke reticulate, må pakken installeres i R:

```R
renv::install("reticulate")
```

Se videoen under og koden [reticulate_kjoring.R](https://github.com/statisticsnorway/ssb-metodebiblioteket/blob/main/Python-og-R/reticulate_kjoring.py) for eksempler.

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/1145855585?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerpolicy="strict-origin-when-cross-origin" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Kjør Python fra R med reticulate"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
